### ISSUE TITLE
Wercker doesn't generate public files

### ISSUE THREAD

**Issue by kidd001** [ArjenSchwarz/wercker-step-hugo-build#20]
Hi There,

I have got Wercker and GitHub setup as what it says in Hugo's documentation, Wercker can successfully deploy and build whenever I commit new stuff. But I just couldn't get Wercker to generate any public files.

The following shows how my wercker.yml is being setup:

box: wercker/default
build:
  steps:
    - arjen/hugo-build:
        version: 0.14
        theme: hyde
        flags: --disableSitemap=true
deploy:
  steps:
    - lukevivier/gh-pages@0.2.1:
        token: $GIT_TOKEN
        domain: www.kocka-gene.io
        basedir: public

Much appreicated if you can spend some time to look into it for me.

Thanks,
Kexin

**Comment by ArjenSchwarz** [comment]
Hi Kexin,

Am I correct in that you're trying to use it with https://github.com/kidd001/kidd001.github.io?
Because I can see in that project that the gh-pages branch is up to date with the contents of the project. To be clear, the gh-pages branch is where the contents of the public directory is pushed, it doesn't get added to the master branch.
Your problem here might be that you've created a user site, which expects the site to be created in the master branch. The easiest solution is to use a project site instead, especially as you're using a custom url. See https://pages.github.com for information on the different types of GitHub Pages sites. 

If you specifically want to keep it as a user site, you will need to make some changes. First you will not be able to have the code in your master branch of that repository, as it should either be in a different repository or branch. The master branch in your github.io repo will then serve the same purpose as the gh-pages branch does in a different repository. The below should replace your existing deploy step and will then push it to the repository where you want it.

```
- install-packages:
    packages: git ssh-client
- leipert/git-push:
     gh_oauth: $GIT_TOKEN
     repo: kidd001/kidd001.github.io
     branch: master
     basedir: public
```

Let me know if this helped.

Cheers,

Arjen

**Comment by kidd001** [comment]
Thank for getting back to me Arjen and sorry for my late reply!

I will give it a try and let you know tonight.

**Comment by kidd001** [comment]
If I want to keep it as a user site, do I have to create a another branch and push my codes to that branch?

Or I can just replace my existing deploy steps with the one you provided?

**Comment by ArjenSchwarz** [comment]
You will have to push your code to a different branch and use the code I provided.

**Comment by kidd001** [comment]
I have created a branch called "develop", and update my existing deploy steps with the one you provided in wercker.yml, then push all the changes to "develop", issues I can see so far in Wercker:

It builds successfully

![image](https://cloud.githubusercontent.com/assets/2474906/12608134/e1d2a3bc-c53e-11e5-8513-05320028df74.png)

But it doesn't deploy as it used to be

![image](https://cloud.githubusercontent.com/assets/2474906/12608155/0822ba20-c53f-11e5-9afc-e432ecc0700f.png)

Any ideas how to solve it?

**Comment by ArjenSchwarz** [comment]
The automatic deploys are something you have to turn on. When you go to settings for your application (the cog in the upper right), you can then select Targets. In Targets you'll have to edit your current deployment target, and set the Auto deploy target to develop.

**Comment by kidd001** [comment]
Thanks for your help Arjen, files are successfully deployed as the screenshot attached.

![image](https://cloud.githubusercontent.com/assets/2474906/12629120/4cd83782-c5ab-11e5-8627-8c95a05bb87d.png)

But I still can't see "public" folder is generated in any of the brunches?

![image](https://cloud.githubusercontent.com/assets/2474906/12629189/9d56ac48-c5ab-11e5-88de-5c559e5ca252.png)

![image](https://cloud.githubusercontent.com/assets/2474906/12629194/a9fecd54-c5ab-11e5-9efb-77ccc375c084.png)

![image](https://cloud.githubusercontent.com/assets/2474906/12629210/b87a313e-c5ab-11e5-9855-9313c2395839.png)

**Comment by ArjenSchwarz** [comment]
It actually won't deploy the _public_ directory, but only its contents as that is what you need. So everything that is present in the _public_ directory, such as the index.html, index.xml, posts, etc. are there, but it won't show the directory.
Your site isn't showing anything yet, as you don't have a theme configured, but I suspect once you add that it should be a visible site. One thing you might consider is to empty the master branch followed by a new deployment, as it now has both the site code and the hugo config, which makes it a bit harder to see what's going on.

**Comment by kidd001** [comment]
theme is already defined in build steps but not deploy steps, does it matter?

![image](https://cloud.githubusercontent.com/assets/2474906/12638358/59acc92c-c601-11e5-88d3-43e0ce901fe5.png)

**Comment by kidd001** [comment]
still not working.....

it's not even showing anything on my local now, weird...

**Comment by ArjenSchwarz** [comment]
Sorry, I probably wasn't clear earlier. I meant that I don't see a theme present in your source code. You will need it to be there, either by having it as submodule (which you'll have to pull in manually in Wercker) or by copying the theme there manually. It needs to be present in the themes directory

**Comment by kidd001** [comment]
It's all working now, thank you very much for your help!

**Comment by ArjenSchwarz** [comment]
That's great, I'm glad you got it all sorted out
