### ISSUE TITLE
After the update, pages are no longer generated

### ISSUE THREAD

**Issue by Skarlso** [ArjenSchwarz/wercker-step-hugo-build#37]
Hi. 

I had to switch back to 0.14 or whatever version there was. After the update, suddenly, pages where no longer being generated from markdown files. The post was bought up on the main index page, but when I was trying to go to the page, it could not be found. 

Once I switched back to using a previous version before the hugo 0.19 defaulting, my blog is generated correctly again. 

Here is the source: https://github.com/Skarlso/blogsource
And the generated pages: https://github.com/Skarlso/skarlso.github.io

though these work correctly now. And I was unable to find anything in the logs...

**Comment by ArjenSchwarz** [comment]
Hi @Skarlso that's strange. Thanks for letting me know though, and I'll have a look to see what's going on. 
The only thing I can think of right now is that maybe there is something you use has been deprecated. I actually had a similar thing when I ran it on one of my test sites. Anyway, I just got into work but I'll look into it tonight or tomorrow and let you know what I can find.

**Comment by Skarlso** [comment]
Hey man. Sorry, I think we are in a different timezone. :) But I'll try to help as much as I can. 

You can see my setup, if you took a look, I don't think I'm using anything special. I don't even have any fancy settings or something. Just plain ol' hugo. :)

Cheers

**Comment by ArjenSchwarz** [comment]
No problem, living in Australia pretty much ensures that I'm not in the same timezone as most others :).

Ok, so I've had a look and I know what the problem is, but it's something to do with how Hugo has changed between 0.18 and 0.19. In other words, the problem only shows up in 0.19 but not in previous versions as you discovered yourself.

When I run Hugo in verbose mode with 0.19 (`hugo --verbose`), it complains that it doesn't see any layouts for posts or terms. I'm guessing that it doesn't fall back to the single or list ones in your theme for some reason.

The easiest way to solve it that I found is to copy _default/single.html and _default/list.html in your theme to _default/post.html and _default/terms.html respectively. After that it will render it correctly.

Cheers

**Comment by Skarlso** [comment]
Awesome man!! 

I'm going to try this out in a couple of minutes.

**Comment by Skarlso** [comment]
Woooot! Worked! :) The post is generated [here](http://skarlso.github.io/2017/03/17/test-new-hugo/). Thanks man. :)
